### ISSUE TITLE
凭现有的内容来看, 无法复刻

### ISSUE THREAD

**Issue by ds2457513911** [NICE-FUTURE/WS-MTST#1]
这个没有说数据结构吧, 而且一个nii.gz格式的文件怎么转换成的那么多npy格式文件的? 这些我好像都没看到啊

**Comment by NICE-FUTURE** [comment]
[https://github.com/NICE-FUTURE/WS-MTST?tab=readme-ov-file#data-preparation](https://github.com/NICE-FUTURE/WS-MTST?tab=readme-ov-file#data-preparation)
