### ISSUE TITLE
Some Issue about Pretrain

### ISSUE THREAD

**Issue by tanjia123456** [NICE-FUTURE/WS-MTST#2]
Hello thanks for your contribution! In the pre-training process, the SelfTrainBraTSDataset function is loaded from the dataset, which has the original data format of nifti. However, your code seems to be in npy format. Would you mind sharing the preprocessing code? Is there anything special about it? My email address is 1248742467@qq.com.

**Comment by NICE-FUTURE** [comment]
Thanks for your interest!

As described in [README](https://github.com/NICE-FUTURE/WS-MTST?tab=readme-ov-file#data-preparation), the preprocessing script I used is based on the following reference:
[https://github.com/Merofine/BrainTumorSegmentation/blob/main/data/BraTS2Dpreprocessing-master/GetTestingSetsFrom2019.ipynb](https://github.com/Merofine/BrainTumorSegmentation/blob/main/data/BraTS2Dpreprocessing-master/GetTestingSetsFrom2019.ipynb)

Best regards.
